Feature/#381 favorite register delete api
SCBJ-7/SCBJ-BE pull request #382
Opened 2024-05-01 02:19 UTC by Aleexender

# 😁 Issue Link
- Close #381 
# 😆 To Reviewers
- 빠른 리뷰 부탁드려요 🥲
# 😚 Reference
- url 링크 (discussion)

# 📌 PR 진행 시 이러한 점들을 참고해 주세요
* Reviewer 분들은 코드 리뷰 시 좋은 코드의 방향을 제시하되, **코드 수정을 강제하지 말아 주세요.**
* Reviewer 분들은 좋은 코드를 발견한 경우, **칭찬과 격려**를 아끼지 말아 주세요.
* Review는 특수한 케이스가 아니면 Reviewer로 지정된 시점 기준으로 **3일 이내에 진행**해 주세요.
* Comment 작성 시 Prefix로 P1, P2, P3 를 적어 주시면 Assignee가 보다 명확하게 Comment에 대해 대응할 수 있어요
  * P1 : **꼭 반영해 주세요** (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
  * P2 : 반영을 **적극적으로 고려**해 주시면 좋을 것 같아요 (Comment)
  * P3 : 이런 방법도 있을 것 같아요~ 등의 **사소한 의견**입니다 (Chore)

2024-05-01 02:48 UTC, Kwonminwoo commented on src/main/java/com/yanolja/scbj/domain/like/service/FavoriteService.java
> +        } catch (EntityNotFoundException e) {
P2: Optional로 처리하는 것 보다 좋은건가?

2024-05-01 02:48 UTC, Kwonminwoo commented on src/main/java/com/yanolja/scbj/domain/like/service/FavoriteService.java
> +        } catch (IllegalArgumentException e) {
P3: 언제 일어날 수 있는 에러야??

2024-05-01 02:50 UTC, Aleexender commented on src/main/java/com/yanolja/scbj/domain/like/service/FavoriteService.java
> +        } catch (EntityNotFoundException e) {
Optional은 외부에있는 라이브러리를 사용할때 사용하는걸로 알고있다고 들어서 옵셔널로 처리할까 말까 하다가 그냥 Optional안쓰고 트라이 캐치로 잡은거긴한데 고치는게 좋을깡??

2024-05-01 02:51 UTC, Aleexender commented on src/main/java/com/yanolja/scbj/domain/like/service/FavoriteService.java
> +        } catch (IllegalArgumentException e) {
혹시라도 null 값 주면 발생되는 에러로 알고이써!

2024-05-01 03:10 UTC, Kwonminwoo commented on src/main/java/com/yanolja/scbj/domain/like/entity/dto/request/FavoriteRegisterRequest.java
> +    boolean favoriteStatement
P3: 항상 true 값이 들어오는 것 아니야?? 어떻게 동작되는지 잘 모르겠다

2024-05-01 03:11 UTC, Aleexender commented on src/main/java/com/yanolja/scbj/domain/like/entity/dto/request/FavoriteRegisterRequest.java
> +    boolean favoriteStatement
아 생각해보니 그렇네...
난 FE 측에서 값 보내줘서 저장해야할줄 알았는데 너말 들어보니까 항상 트루값이 들어오는게 맞겠다

2024-05-01 03:13 UTC, Kwonminwoo commented on src/main/java/com/yanolja/scbj/domain/like/service/FavoriteService.java
> +        } catch (EntityNotFoundException e) {
외부 라이브러리?? 모르겠다 너가 맞다고 생각하는거로 해도 돼
기능은 같은데 optional로 처리하는 것 보다 복잡하니까 굳이 저렇게 쓰지 않을 것 같아 나는

2024-05-01 03:17 UTC, Aleexender commented on src/main/java/com/yanolja/scbj/domain/like/service/FavoriteService.java
> +        } catch (EntityNotFoundException e) {
https://mangkyu.tistory.com/203

이런거 비슷한거 옛날에 보고 적용해 본거긴한데 나중에 이거 정리해보고 디스커션에다가 올려놔볼겡!

2024-05-05 02:41 UTC, wocjf0513 requested changes

2024-05-05 02:41 UTC, wocjf0513 commented on src/main/java/com/yanolja/scbj/domain/like/entity/Favorite.java
찜하기 취소하면, 삭제하는 로직이 있는 거 같은데 
결국, 찜 튜플의 찜 상태가 언제나 true일 거 같은데 
찜 상태라는 필드를 둔 이유가 궁금해

2024-05-05 03:17 UTC, Aleexender commented on src/main/java/com/yanolja/scbj/domain/like/entity/Favorite.java
아 그렇네 그냥 저거 없애야겠다

2024-05-06 01:10 UTC, wocjf0513 approved these changes

2024-05-08 12:12 UTC, merged